### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by cnzbq** [open-dingtalk/dingtalk-stream-sdk-java-quick-start#3]
### maven依赖
```xml
<dependency>
    <groupId>com.dingtalk.open</groupId>
    <artifactId>app-stream-client</artifactId>
    <version>1.0.1</version>
</dependency>
```

### 代码
```java
import com.alibaba.fastjson2.JSONObject;
import com.dingtalk.open.app.api.callback.OpenDingTalkCallbackListener;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class RobotMsgCallbackConsumer implements OpenDingTalkCallbackListener<JSONObject, JSONObject> {
    @Override
    public JSONObject execute(JSONObject request) {
        try {
            JSONObject text = request.getJSONObject("text");   //java.lang.ClassCastException
            if (text != null) {
                String msg = text.getString("content").trim();
                String openConversationId = request.getString("conversationId");
            }

            log.info("接收到了消息：{}", request.toJSONString());

        } catch (Exception e) {
            log.error("receive group message by robot error:" + e.getMessage(), e);
        }
        return new JSONObject();
    }
}
```

### 异常日志
```java
java.lang.ClassCastException: class com.alibaba.fastjson.JSONObject cannot be cast to class com.alibaba.fastjson2.JSONObject (com.alibaba.fastjson.JSONObject and com.alibaba.fastjson2.JSONObject are in unnamed module of loader 'app')
	at ~.~.dingrobot.handler.RobotMsgCallbackConsumer.execute(RobotMsgCallbackConsumer.java:13) ~[classes/:na]
	at com.dingtalk.open.app.api.callback.SimpleMethod.execute(SimpleMethod.java:22) ~[app-stream-client-1.0.1.jar:na]
	at com.dingtalk.open.app.api.callback.CallbackCommandExecutor.execute(CallbackCommandExecutor.java:50) ~[app-stream-client-1.0.1.jar:na]
	at com.dingtalk.open.app.api.command.CommandDispatcher.execute(CommandDispatcher.java:38) ~[app-stream-client-1.0.1.jar:na]
	at com.dingtalk.open.app.api.protocol.AppServiceListener.lambda$receive$0(AppServiceListener.java:30) ~[app-stream-client-1.0.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[app-stream-client-1.0.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by qwangseu** [comment]
fastjson的版本有冲突，可以拉取最新的工程代码使用具体的机器人出参入参model类代替JSONObject

**Comment by chzealot** [comment]
这个问题原因是 fastjson v1 和 v2的类名冲突，解决方案有两个

1. （推荐）将 Stream SDK （app-stream-client） 升级到最新版本（1.0.3），并参考最新的示例代码 （不显示依赖 fastjson）：https://github.com/open-dingtalk/dingtalk-stream-sdk-java-quick-start/blob/main/src/main/java/org/example/callback/robot/RobotMsgCallbackConsumer.java
2. 为JSONObject对象添加完整的包路径，com.....JSONObject
